### ISSUE TITLE
White text on yellow background in "WARNING" items

### ISSUE THREAD

**Issue by cstratopoulos** [ixm-one/docs.ixm.one#1]
Hi! I was just reading the IXM documentation and got to the [overrides](https://docs.ixm.one/en/api/override.html) page which has a "WARNING" item. Wanted to point out that right now the explanatory text looks like white text on a light yellow background, which is not readable without highlighting the text.

**Comment by slurps-mad-rips** [comment]
I've transfered this issue to the documentation repo so I can focus on the docs related issues after the current refactor has been completed.

**Comment by bruxisma** [comment]
Hi, I'm going to be closing this as IXM is relaunching (with this specific issue fixed in the docs) on November 1st. While the warning in question is no longer present (we don't really override CMake's definition), I briefly imported it into a document and took a screenshot.

![image](https://user-images.githubusercontent.com/63051/191200532-b6445c03-f985-4ef9-9e5f-c6ecbea3913a.png)

I'm sorry this all took so long to get to (including actually making IXM decent 😅) but well life and the pandemic got in the way. Even if you don't end up using IXM, thanks for originally reporting this issue! I do appreciate it

I'll be deleting this repository come Nov. 1st as docs will be living alongside the source code.
